apiVersion: v1
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://svc-db:5432/docker_book
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.username=book
    spring.datasource.password=book
    logging.level.org.springframework.web: DEBUG
    logging.level.org.hibernate: ERROR
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rest-service
  namespace: docker-book
